package com.aibench.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.List;

/**
 * Phase C / Layer 3 — brand-fork variant of
 * {@link RegionalScenarioTestGenerator}. Walks
 * {@code banking-app/generated-brands/} and emits a
 * {@code <Prefix>ScenarioMatrixTest.java} alongside the existing brand-profile
 * test for each module. Each generated file contains roughly 20 @Test methods
 * covering BrandProfile, MarketingCopy, PricingOverride, OnboardingFlow,
 * and CustomerCommunication.
 *
 * <p>Idempotent: rerunning overwrites the {@code *ScenarioMatrixTest.java}
 * files but leaves all other sources untouched.
 */
public class BrandScenarioTestGenerator {

    public static void main(String[] args) throws IOException {
        Path brandsRoot = resolveRoot(args);
        if (!Files.isDirectory(brandsRoot)) {
            throw new IllegalStateException("generated-brands not found at " + brandsRoot);
        }

        List<Path> moduleDirs;
        try (var stream = Files.list(brandsRoot)) {
            moduleDirs = stream.filter(Files::isDirectory).sorted().toList();
        }

        int generated = 0;
        long totalLoc = 0;
        for (Path moduleDir : moduleDirs) {
            ModuleInfo info = inspectModule(moduleDir);
            if (info == null) continue;
            String src = scenarioTest(info);
            Path testFile = info.testDir.resolve(info.classPrefix + "ScenarioMatrixTest.java");
            Files.createDirectories(testFile.getParent());
            Files.writeString(testFile, src, StandardCharsets.UTF_8);
            generated++;
            totalLoc += src.lines().count();
        }
        System.out.println("Generated " + generated + " brand scenario tests (~"
                + totalLoc + " LOC)");
    }

    private static Path resolveRoot(String[] args) {
        if (args.length > 0) return Paths.get(args[0]);
        Path cwd = Paths.get("").toAbsolutePath();
        for (int i = 0; i < 4; i++) {
            Path candidate = cwd.resolve("banking-app").resolve("generated-brands");
            if (Files.isDirectory(candidate)) return candidate;
            if (cwd.getParent() == null) break;
            cwd = cwd.getParent();
        }
        throw new IllegalStateException("Cannot find banking-app/generated-brands");
    }

    private static ModuleInfo inspectModule(Path moduleDir) throws IOException {
        Path mainJava = moduleDir.resolve("src/main/java");
        if (!Files.isDirectory(mainJava)) return null;

        Path profileFile;
        try (var stream = Files.walk(mainJava)) {
            profileFile = stream
                    .filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith("BrandProfile.java"))
                    .min(Comparator.comparing(Path::toString))
                    .orElse(null);
        }
        if (profileFile == null) return null;

        String fileName = profileFile.getFileName().toString();
        String classPrefix = fileName.substring(0,
                fileName.length() - "BrandProfile.java".length());
        String pkg = readPackage(profileFile);
        if (pkg == null) return null;

        Path testDir = moduleDir.resolve("src/test/java/" + pkg.replace('.', '/'));
        return new ModuleInfo(pkg, classPrefix, testDir);
    }

    private static String readPackage(Path javaFile) throws IOException {
        for (String line : Files.readAllLines(javaFile, StandardCharsets.UTF_8)) {
            String trimmed = line.trim();
            if (trimmed.startsWith("package ") && trimmed.endsWith(";")) {
                return trimmed.substring("package ".length(), trimmed.length() - 1).trim();
            }
        }
        return null;
    }

    private static String scenarioTest(ModuleInfo info) {
        return ("""
                package %PKG%;

                import java.math.BigDecimal;
                import org.junit.jupiter.api.Test;
                import static org.assertj.core.api.Assertions.assertThat;

                /**
                 * Auto-generated brand-scenario tests for the %PREFIX% brand fork.
                 * Generated by {@code com.aibench.codegen.BrandScenarioTestGenerator}.
                 *
                 * <p>Coverage: brand identity invariants, age-bound checks,
                 * marketing copy presence, pricing-override math, onboarding
                 * step ordering, and customer-communication footers.
                 */
                class %PREFIX%ScenarioMatrixTest {

                    @Test
                    void brand_profile_identity_fields_present() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.brandCode()).isNotBlank();
                        assertThat(p.displayName()).isNotBlank();
                        assertThat(p.tagline()).isNotBlank();
                    }

                    @Test
                    void brand_primary_color_is_hex_format() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.primaryColor()).startsWith("#");
                        assertThat(p.primaryColor().length()).isIn(4, 7, 9);
                    }

                    @Test
                    void brand_minimum_age_is_realistic() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.minimumAge()).isBetween(0, 70);
                    }

                    @Test
                    void brand_founded_year_is_in_modern_banking_era() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.brandFounded()).isBetween(1850, 2030);
                    }

                    @Test
                    void brand_age_in_years_is_consistent_with_founded() {
                        var p = new %PREFIX%BrandProfile();
                        int years = p.ageInYears(2026);
                        assertThat(years).isEqualTo(2026 - p.brandFounded());
                    }

                    @Test
                    void brand_heritage_predicate_consistent_with_age() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.isHeritageBrand(2026))
                                .isEqualTo(p.ageInYears(2026) >= 50);
                    }

                    @Test
                    void brand_value_statements_are_nonempty() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.brandValueStatements()).isNotEmpty();
                        for (String s : p.brandValueStatements()) {
                            assertThat(s).isNotBlank();
                        }
                    }

                    @Test
                    void brand_promise_headline_is_present() {
                        var p = new %PREFIX%BrandProfile();
                        assertThat(p.brandPromiseHeadline()).isNotBlank();
                    }

                    @Test
                    void marketing_copy_hero_headline_present() {
                        var m = new %PREFIX%MarketingCopy();
                        assertThat(m.heroHeadline()).isNotBlank();
                        assertThat(m.subheadline()).isNotBlank();
                    }

                    @Test
                    void marketing_call_to_action_verb_is_concise() {
                        var m = new %PREFIX%MarketingCopy();
                        assertThat(m.callToActionVerb()).isNotBlank();
                        assertThat(m.callToActionVerb().length()).isLessThanOrEqualTo(40);
                    }

                    @Test
                    void marketing_footer_legal_is_present() {
                        var m = new %PREFIX%MarketingCopy();
                        assertThat(m.footerLegal()).isNotBlank();
                    }

                    @Test
                    void pricing_apy_bonus_is_finite_bps() {
                        var po = new %PREFIX%PricingOverride();
                        assertThat(po.apyBonusBps()).isNotNull();
                        // BPS bonuses across our brand catalog are within ±200bps.
                        assertThat(po.apyBonusBps().abs())
                                .isLessThanOrEqualTo(new BigDecimal("200"));
                    }

                    @Test
                    void pricing_adjust_apy_is_idempotent_at_zero_bonus_when_bonus_zero() {
                        var po = new %PREFIX%PricingOverride();
                        var nationalApy = new BigDecimal("0.0300");
                        var adjusted = po.adjustApy(nationalApy);
                        if (po.apyBonusBps().signum() == 0) {
                            assertThat(adjusted).isEqualByComparingTo(nationalApy);
                        }
                    }

                    @Test
                    void pricing_adjust_monthly_fee_returns_value() {
                        var po = new %PREFIX%PricingOverride();
                        var national = new BigDecimal("12.00");
                        var adjusted = po.adjustMonthlyFee(national);
                        assertThat(adjusted).isNotNull();
                        assertThat(adjusted.signum()).isGreaterThanOrEqualTo(0);
                    }

                    @Test
                    void pricing_promotional_flag_is_a_boolean() {
                        var po = new %PREFIX%PricingOverride();
                        // Boolean predicate, must not throw.
                        boolean unused = po.isPromotionalRateActive();
                        assertThat(unused).isIn(true, false);
                    }

                    @Test
                    void onboarding_flow_has_at_least_one_step() {
                        var of = new %PREFIX%OnboardingFlow();
                        assertThat(of.stepCount()).isGreaterThanOrEqualTo(1);
                        assertThat(of.steps()).hasSize(of.stepCount());
                    }

                    @Test
                    void onboarding_steps_are_sequenced_uniquely() {
                        var of = new %PREFIX%OnboardingFlow();
                        var seen = new java.util.HashSet<Integer>();
                        for (var step : of.steps()) {
                            assertThat(step.code()).isNotBlank();
                            assertThat(step.label()).isNotBlank();
                            assertThat(step.sequenceNumber()).isGreaterThanOrEqualTo(0);
                            assertThat(seen.add(step.sequenceNumber()))
                                    .as("sequence " + step.sequenceNumber() + " was duplicated")
                                    .isTrue();
                        }
                    }

                    @Test
                    void onboarding_estimated_minutes_is_reasonable() {
                        var of = new %PREFIX%OnboardingFlow();
                        assertThat(of.estimatedMinutes()).isBetween(1L, 120L);
                    }

                    @Test
                    void communication_sender_address_looks_like_email() {
                        var c = new %PREFIX%CustomerCommunication();
                        assertThat(c.senderFromAddress()).contains("@");
                    }

                    @Test
                    void communication_signature_block_present_and_unsubscribe_footer_legal() {
                        var c = new %PREFIX%CustomerCommunication();
                        assertThat(c.signatureBlock()).isNotBlank();
                        assertThat(c.unsubscribeFooter()).isNotBlank();
                    }
                }
                """)
                .replace("%PKG%", info.pkg)
                .replace("%PREFIX%", info.classPrefix);
    }

    private record ModuleInfo(String pkg, String classPrefix, Path testDir) {}
}
