package com.aibench.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.List;

/**
 * Phase C / Layer 3 — channel-fork variant of
 * {@link RegionalScenarioTestGenerator}. Walks
 * {@code banking-app/generated-channels/} and writes a
 * {@code <Prefix>ScenarioMatrixTest.java} alongside the existing
 * SessionConfig test for each module. Each generated file contains roughly
 * 20 @Test methods that exercise SessionConfig timeouts, AuthenticationPolicy
 * factor sets, FeatureGating availability, UiCopy locale handling, and
 * ErrorTranslator fallback behavior.
 *
 * <p>Idempotent: rerunning overwrites the {@code *ScenarioMatrixTest.java}
 * files but leaves all other sources untouched.
 */
public class ChannelScenarioTestGenerator {

    public static void main(String[] args) throws IOException {
        Path channelsRoot = resolveRoot(args);
        if (!Files.isDirectory(channelsRoot)) {
            throw new IllegalStateException("generated-channels not found at " + channelsRoot);
        }

        List<Path> moduleDirs;
        try (var stream = Files.list(channelsRoot)) {
            moduleDirs = stream.filter(Files::isDirectory).sorted().toList();
        }

        int generated = 0;
        long totalLoc = 0;
        for (Path moduleDir : moduleDirs) {
            ModuleInfo info = inspectModule(moduleDir);
            if (info == null) continue;
            String src = scenarioTest(info);
            Path testFile = info.testDir.resolve(info.classPrefix + "ScenarioMatrixTest.java");
            Files.createDirectories(testFile.getParent());
            Files.writeString(testFile, src, StandardCharsets.UTF_8);
            generated++;
            totalLoc += src.lines().count();
        }
        System.out.println("Generated " + generated + " channel scenario tests (~"
                + totalLoc + " LOC)");
    }

    private static Path resolveRoot(String[] args) {
        if (args.length > 0) return Paths.get(args[0]);
        Path cwd = Paths.get("").toAbsolutePath();
        for (int i = 0; i < 4; i++) {
            Path candidate = cwd.resolve("banking-app").resolve("generated-channels");
            if (Files.isDirectory(candidate)) return candidate;
            if (cwd.getParent() == null) break;
            cwd = cwd.getParent();
        }
        throw new IllegalStateException("Cannot find banking-app/generated-channels");
    }

    private static ModuleInfo inspectModule(Path moduleDir) throws IOException {
        Path mainJava = moduleDir.resolve("src/main/java");
        if (!Files.isDirectory(mainJava)) return null;

        Path sessionFile;
        try (var stream = Files.walk(mainJava)) {
            sessionFile = stream
                    .filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith("SessionConfig.java"))
                    .min(Comparator.comparing(Path::toString))
                    .orElse(null);
        }
        if (sessionFile == null) return null;

        String fileName = sessionFile.getFileName().toString();
        String classPrefix = fileName.substring(0,
                fileName.length() - "SessionConfig.java".length());
        String pkg = readPackage(sessionFile);
        if (pkg == null) return null;

        Path testDir = moduleDir.resolve("src/test/java/" + pkg.replace('.', '/'));
        return new ModuleInfo(pkg, classPrefix, testDir);
    }

    private static String readPackage(Path javaFile) throws IOException {
        for (String line : Files.readAllLines(javaFile, StandardCharsets.UTF_8)) {
            String trimmed = line.trim();
            if (trimmed.startsWith("package ") && trimmed.endsWith(";")) {
                return trimmed.substring("package ".length(), trimmed.length() - 1).trim();
            }
        }
        return null;
    }

    private static String scenarioTest(ModuleInfo info) {
        return ("""
                package %PKG%;

                import java.time.Duration;
                import java.util.Locale;
                import java.util.Map;
                import org.junit.jupiter.api.Test;
                import static org.assertj.core.api.Assertions.assertThat;

                /**
                 * Auto-generated channel-scenario tests for the %PREFIX% channel
                 * fork. Generated by
                 * {@code com.aibench.codegen.ChannelScenarioTestGenerator}
                 * using only the public APIs already present.
                 *
                 * <p>Coverage: session-timeout invariants, auth-factor sanity,
                 * feature-gating consistency, multi-locale UI copy, error-code
                 * translation fallbacks, event tracker accumulation.
                 */
                class %PREFIX%ScenarioMatrixTest {

                    @Test
                    void session_idle_timeout_does_not_exceed_absolute_timeout() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.idleTimeout()).isLessThanOrEqualTo(cfg.absoluteTimeout());
                    }

                    @Test
                    void session_refresh_interval_is_shorter_than_idle_timeout() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.refreshInterval()).isLessThan(cfg.idleTimeout());
                    }

                    @Test
                    void session_supports_at_least_one_concurrent_session() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.maxConcurrentSessions()).isGreaterThanOrEqualTo(1);
                    }

                    @Test
                    void session_target_latency_is_realistic() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.targetLatencyMs()).isBetween(50, 30_000);
                    }

                    @Test
                    void exceeds_latency_target_at_double_the_target() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.exceedsLatencyTarget(cfg.targetLatencyMs() * 2L)).isTrue();
                    }

                    @Test
                    void exceeds_latency_target_at_one_below_is_false() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.exceedsLatencyTarget(cfg.targetLatencyMs() - 1L)).isFalse();
                    }

                    @Test
                    void device_class_is_named() {
                        var cfg = new %PREFIX%SessionConfig();
                        assertThat(cfg.deviceClass()).isNotBlank();
                    }

                    @Test
                    void auth_policy_password_is_among_base_factors_or_strong_alternative() {
                        var auth = new %PREFIX%AuthenticationPolicy();
                        assertThat(auth.baseFactors()).isNotEmpty();
                        assertThat(auth.maxFailedAttempts()).isBetween(1, 20);
                    }

                    @Test
                    void auth_policy_step_up_triggers_have_required_factors() {
                        var auth = new %PREFIX%AuthenticationPolicy();
                        for (var trigger : auth.stepUpTriggers()) {
                            assertThat(trigger.requiredFactors()).isNotEmpty();
                            assertThat(trigger.reason()).isNotBlank();
                        }
                    }

                    @Test
                    void auth_strength_label_is_not_blank() {
                        var auth = new %PREFIX%AuthenticationPolicy();
                        assertThat(auth.authStrength()).isNotBlank();
                    }

                    @Test
                    void feature_gating_view_balance_always_available() {
                        var fg = new %PREFIX%FeatureGating();
                        assertThat(fg.isFeatureAvailable("VIEW_BALANCE")).isTrue();
                    }

                    @Test
                    void feature_gating_unknown_feature_unavailable() {
                        var fg = new %PREFIX%FeatureGating();
                        assertThat(fg.isFeatureAvailable("INTERPLANETARY_TRANSFER")).isFalse();
                    }

                    @Test
                    void feature_gating_available_features_is_nonempty() {
                        var fg = new %PREFIX%FeatureGating();
                        assertThat(fg.availableFeatures()).isNotEmpty();
                    }

                    @Test
                    void feature_gating_predicates_consistent_with_set_membership() {
                        var fg = new %PREFIX%FeatureGating();
                        for (var feature : fg.availableFeatures()) {
                            assertThat(fg.isFeatureAvailable(feature))
                                    .as("feature " + feature)
                                    .isTrue();
                        }
                    }

                    @Test
                    void ui_copy_welcome_renders_in_english_and_spanish() {
                        var ui = new %PREFIX%UiCopy();
                        assertThat(ui.welcomeHeadline(Locale.ENGLISH)).isNotBlank();
                        assertThat(ui.welcomeHeadline(new Locale("es"))).isNotBlank();
                    }

                    @Test
                    void ui_copy_confirm_deposit_prompt_is_locale_aware() {
                        var ui = new %PREFIX%UiCopy();
                        assertThat(ui.confirmDepositPrompt(Locale.ENGLISH)).isNotBlank();
                    }

                    @Test
                    void ui_copy_recommended_max_chars_is_positive() {
                        var ui = new %PREFIX%UiCopy();
                        assertThat(ui.recommendedCopyMaxChars()).isGreaterThan(0);
                    }

                    @Test
                    void ui_copy_error_message_map_returns_a_map() {
                        var ui = new %PREFIX%UiCopy();
                        Map<String, String> map = ui.errorMessageMap(Locale.ENGLISH);
                        assertThat(map).isNotNull();
                    }

                    @Test
                    void error_translator_fallback_returned_for_unknown_codes() {
                        var et = new %PREFIX%ErrorTranslator();
                        assertThat(et.translateWithFallback("NOPE_NOT_A_CODE", "fallback"))
                                .isEqualTo("fallback");
                    }

                    @Test
                    void event_tracker_records_and_counts() {
                        var tracker = new %PREFIX%EventTracker();
                        tracker.track("page.view");
                        tracker.track("page.view");
                        tracker.track("button.click");
                        assertThat(tracker.count("page.view")).isEqualTo(2);
                        assertThat(tracker.totalEvents()).isEqualTo(3);
                        tracker.reset();
                        assertThat(tracker.totalEvents()).isZero();
                    }
                }
                """)
                .replace("%PKG%", info.pkg)
                .replace("%PREFIX%", info.classPrefix);
    }

    private record ModuleInfo(String pkg, String classPrefix, Path testDir) {}
}
