package com.aibench.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.List;

/**
 * Phase C / Layer 3 — NACHA SEC-code variant of
 * {@link RegionalScenarioTestGenerator}. Walks
 * {@code banking-app/generated-nacha/} and writes a
 * {@code <SEC>ScenarioMatrixTest.java} alongside the existing processor
 * test for each SEC-code module.
 *
 * <p>Each generated file contains roughly 18 @Test methods covering the
 * Processor / Entry / ReturnProcessor / AuthorizationCheck APIs that are
 * common across every SEC code.
 *
 * <p>Idempotent.
 */
public class NachaScenarioTestGenerator {

    public static void main(String[] args) throws IOException {
        Path nachaRoot = resolveRoot(args);
        if (!Files.isDirectory(nachaRoot)) {
            throw new IllegalStateException("generated-nacha not found at " + nachaRoot);
        }

        List<Path> moduleDirs;
        try (var stream = Files.list(nachaRoot)) {
            moduleDirs = stream.filter(Files::isDirectory).sorted().toList();
        }

        int generated = 0;
        long totalLoc = 0;
        for (Path moduleDir : moduleDirs) {
            ModuleInfo info = inspectModule(moduleDir);
            if (info == null) continue;
            String src = scenarioTest(info);
            Path testFile = info.testDir.resolve(info.classPrefix + "ScenarioMatrixTest.java");
            Files.createDirectories(testFile.getParent());
            Files.writeString(testFile, src, StandardCharsets.UTF_8);
            generated++;
            totalLoc += src.lines().count();
        }
        System.out.println("Generated " + generated + " NACHA scenario tests (~"
                + totalLoc + " LOC)");
    }

    private static Path resolveRoot(String[] args) {
        if (args.length > 0) return Paths.get(args[0]);
        Path cwd = Paths.get("").toAbsolutePath();
        for (int i = 0; i < 4; i++) {
            Path candidate = cwd.resolve("banking-app").resolve("generated-nacha");
            if (Files.isDirectory(candidate)) return candidate;
            if (cwd.getParent() == null) break;
            cwd = cwd.getParent();
        }
        throw new IllegalStateException("Cannot find banking-app/generated-nacha");
    }

    private static ModuleInfo inspectModule(Path moduleDir) throws IOException {
        Path mainJava = moduleDir.resolve("src/main/java");
        if (!Files.isDirectory(mainJava)) return null;

        Path processorFile;
        try (var stream = Files.walk(mainJava)) {
            processorFile = stream
                    .filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith("Processor.java"))
                    .filter(p -> !p.getFileName().toString().endsWith("ReturnProcessor.java"))
                    .min(Comparator.comparing(Path::toString))
                    .orElse(null);
        }
        if (processorFile == null) return null;

        String fileName = processorFile.getFileName().toString();
        String classPrefix = fileName.substring(0,
                fileName.length() - "Processor.java".length());
        String pkg = readPackage(processorFile);
        if (pkg == null) return null;

        Path testDir = moduleDir.resolve("src/test/java/" + pkg.replace('.', '/'));
        return new ModuleInfo(pkg, classPrefix, testDir);
    }

    private static String readPackage(Path javaFile) throws IOException {
        for (String line : Files.readAllLines(javaFile, StandardCharsets.UTF_8)) {
            String trimmed = line.trim();
            if (trimmed.startsWith("package ") && trimmed.endsWith(";")) {
                return trimmed.substring("package ".length(), trimmed.length() - 1).trim();
            }
        }
        return null;
    }

    private static String scenarioTest(ModuleInfo info) {
        return ("""
                package %PKG%;

                import java.math.BigDecimal;
                import java.time.LocalDate;
                import java.util.List;
                import java.util.Map;
                import org.junit.jupiter.api.Test;
                import static org.assertj.core.api.Assertions.assertThat;
                import static org.assertj.core.api.Assertions.assertThatThrownBy;

                /**
                 * Auto-generated scenario tests for the %PREFIX% NACHA SEC-code
                 * processor. Generated by
                 * {@code com.aibench.codegen.NachaScenarioTestGenerator}.
                 *
                 * <p>Coverage: SEC-code identity, batch counters, entry validation
                 * (routing length / amount sign), R-code catalog completeness,
                 * return-window enforcement, authorization-signature flags.
                 */
                class %PREFIX%ScenarioMatrixTest {

                    private final %PREFIX%Processor processor = new %PREFIX%Processor();
                    private final %PREFIX%ReturnProcessor returnProcessor = new %PREFIX%ReturnProcessor();
                    private final %PREFIX%AuthorizationCheck authCheck = new %PREFIX%AuthorizationCheck();

                    @Test
                    void sec_code_is_short_and_uppercase() {
                        var sec = processor.secCode();
                        assertThat(sec).isNotBlank();
                        assertThat(sec.length()).isBetween(2, 4);
                        assertThat(sec).isEqualTo(sec.toUpperCase());
                    }

                    @Test
                    void classification_is_consumer_or_corporate() {
                        assertThat(processor.classification())
                                .isIn("CONSUMER", "CORPORATE");
                    }

                    @Test
                    void empty_batch_yields_empty_accepted_and_rejected() {
                        var result = processor.processBatch(List.of(), Map.of());
                        assertThat(result.accepted()).isEmpty();
                        assertThat(result.rejected()).isEmpty();
                        assertThat(result.rejectionReasons()).isEmpty();
                    }

                    @Test
                    void batch_counter_increments_per_invocation() {
                        long before = processor.batchesProcessed();
                        processor.processBatch(List.of(), Map.of());
                        processor.processBatch(List.of(), Map.of());
                        assertThat(processor.batchesProcessed() - before).isEqualTo(2);
                    }

                    @Test
                    void process_batch_null_entries_throws_npe() {
                        assertThatThrownBy(() ->
                                processor.processBatch(null, Map.of()))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void process_batch_handles_null_auth_map() {
                        var result = processor.processBatch(List.of(), null);
                        assertThat(result).isNotNull();
                    }

                    @Test
                    void entry_rejects_short_routing_number() {
                        assertThatThrownBy(() -> new %PREFIX%Entry(
                                "22", "12345", "0123456789",
                                BigDecimal.TEN, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null))
                                .isInstanceOf(IllegalArgumentException.class)
                                .hasMessageContaining("9");
                    }

                    @Test
                    void entry_rejects_negative_amount() {
                        assertThatThrownBy(() -> new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                new BigDecimal("-1"), "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null))
                                .isInstanceOf(IllegalArgumentException.class)
                                .hasMessageContaining("non-negative");
                    }

                    @Test
                    void entry_rejects_null_routing_number() {
                        assertThatThrownBy(() -> new %PREFIX%Entry(
                                "22", null, "0123456789",
                                BigDecimal.TEN, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void entry_rejects_null_amount() {
                        assertThatThrownBy(() -> new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                null, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void entry_zero_amount_is_accepted() {
                        // NACHA allows pre-notification zero-dollar entries.
                        var entry = new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                BigDecimal.ZERO, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null);
                        assertThat(entry.amount().signum()).isZero();
                    }

                    @Test
                    void entry_sec_code_matches_processor() {
                        var entry = new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                BigDecimal.TEN, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null);
                        assertThat(entry.secCode()).isEqualTo(processor.secCode());
                    }

                    @Test
                    void entry_consumer_corporate_predicates_are_mutually_exclusive() {
                        var entry = new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                BigDecimal.TEN, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null);
                        assertThat(entry.isConsumer() && entry.isCorporate()).isFalse();
                    }

                    @Test
                    void return_processor_publishes_standard_r_code_set() {
                        assertThat(%PREFIX%ReturnProcessor.STANDARD_R_CODES)
                                .isNotEmpty()
                                .contains("R01");
                    }

                    @Test
                    void return_window_days_is_non_negative() {
                        assertThat(returnProcessor.returnWindowDays())
                                .isGreaterThanOrEqualTo(0);
                    }

                    @Test
                    void return_processor_rejects_unknown_rcode() {
                        var outcome = returnProcessor.process(
                                new %PREFIX%ReturnProcessor.ReturnEntry(
                                        "Z99", "T0001", LocalDate.of(2026, 4, 1),
                                        LocalDate.of(2026, 4, 5), "test"));
                        assertThat(outcome.accepted()).isFalse();
                        assertThat(outcome.disposition()).isNotBlank();
                    }

                    @Test
                    void authorization_signature_flags_are_booleans() {
                        // Just call them to ensure no NPE; values vary by SEC code.
                        boolean wet = authCheck.requiresWetSignature();
                        boolean electronic = authCheck.electronicSignatureAcceptable();
                        assertThat(wet).isIn(true, false);
                        assertThat(electronic).isIn(true, false);
                    }

                    @Test
                    void authorization_verify_returns_outcome_consistent_with_violations() {
                        var entry = new %PREFIX%Entry(
                                "22", "012345678", "0123456789",
                                BigDecimal.TEN, "ID1", "Name", "",
                                LocalDate.of(2026, 4, 19), "T1", null);
                        var outcome = authCheck.verify(entry, null);
                        assertThat(outcome).isNotNull();
                        assertThat(outcome.ok()).isEqualTo(outcome.violations().isEmpty());
                    }
                }
                """)
                .replace("%PKG%", info.pkg)
                .replace("%PREFIX%", info.classPrefix);
    }

    private record ModuleInfo(String pkg, String classPrefix, Path testDir) {}
}
