package com.aibench.codegen;

import com.aibench.codegen.RegionalForkGenerator.StateSpec;

/**
 * Templates for per-state regional product forks. Each fork emits ~600 LOC
 * across five source files + a test.
 */
final class RegionalTemplates {

    private RegionalTemplates() {}

    static String buildGradle() {
        return """
                dependencies {
                    testImplementation("org.junit.jupiter:junit-jupiter")
                    testImplementation("org.assertj:assertj-core")
                }
                """;
    }

    static String packageInfo(String pkg, String foundation, StateSpec s) {
        return """
                /**
                 * %FOUND% regional fork for %NAME% (%CODE%), %REGION%.
                 *
                 * <p>Generated by {@code RegionalForkGenerator}. State-level
                 * overrides include Reg DD disclosure variations, escheatment rules,
                 * state tax withholding for retirement products, and FDIC regional
                 * examiner assignment (%FDIC%).
                 */
                package %PKG%;
                """
                .replace("%PKG%", pkg)
                .replace("%FOUND%", foundation)
                .replace("%CODE%", s.code())
                .replace("%NAME%", s.name())
                .replace("%REGION%", s.region())
                .replace("%FDIC%", s.fdicRegion());
    }

    static String profile(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.math.BigDecimal;
                import java.util.Objects;

                /**
                 * Jurisdiction profile for %FOUND% as offered in %NAME% (%CODE%).
                 * Captures state-specific overrides that diverge from the
                 * national product specification.
                 */
                public final class %CLS%Profile {

                    private final String stateCode;
                    private final String stateName;
                    private final String region;
                    private final BigDecimal salesTaxRate;
                    private final String fdicRegion;
                    private final int escheatmentDormancyYears;
                    private final boolean offersSpanishLanguageSupport;
                    private final boolean requiresPrintedDisclosure;
                    private final String stateBankingAuthority;

                    public %CLS%Profile() {
                        this.stateCode = "%CODE%";
                        this.stateName = "%NAME%";
                        this.region = "%REGION%";
                        this.salesTaxRate = new BigDecimal("%TAX%");
                        this.fdicRegion = "%FDIC%";
                        this.escheatmentDormancyYears = defaultEscheatmentYears();
                        this.offersSpanishLanguageSupport = offersSpanish();
                        this.requiresPrintedDisclosure = printedDisclosureRequired();
                        this.stateBankingAuthority = stateAuthorityName();
                    }

                    public String stateCode() { return stateCode; }
                    public String stateName() { return stateName; }
                    public String region() { return region; }
                    public BigDecimal salesTaxRate() { return salesTaxRate; }
                    public String fdicRegion() { return fdicRegion; }
                    public int escheatmentDormancyYears() { return escheatmentDormancyYears; }
                    public boolean offersSpanishLanguageSupport() { return offersSpanishLanguageSupport; }
                    public boolean requiresPrintedDisclosure() { return requiresPrintedDisclosure; }
                    public String stateBankingAuthority() { return stateBankingAuthority; }

                    public boolean isNoSalesTaxState() {
                        return salesTaxRate.signum() == 0;
                    }

                    public BigDecimal applyStateFeeTax(BigDecimal baseFee) {
                        Objects.requireNonNull(baseFee, "baseFee");
                        return baseFee.multiply(BigDecimal.ONE.add(salesTaxRate))
                                .setScale(2, java.math.RoundingMode.HALF_EVEN);
                    }

                    private int defaultEscheatmentYears() {
                        return switch (stateCode) {
                            case "DE" -> 5;
                            case "CA", "FL", "TX", "NY", "IL" -> 3;
                            default -> 5;
                        };
                    }

                    private boolean offersSpanish() {
                        return switch (stateCode) {
                            case "CA", "TX", "FL", "NM", "AZ", "NV", "NY", "NJ", "IL", "CO" -> true;
                            default -> false;
                        };
                    }

                    private boolean printedDisclosureRequired() {
                        return switch (stateCode) {
                            case "CA", "NY", "IL", "MA", "CT" -> true;
                            default -> false;
                        };
                    }

                    private String stateAuthorityName() {
                        return switch (stateCode) {
                            case "NY" -> "New York Department of Financial Services";
                            case "CA" -> "California Department of Financial Protection and Innovation";
                            case "TX" -> "Texas Department of Banking";
                            case "FL" -> "Florida Office of Financial Regulation";
                            case "IL" -> "Illinois Department of Financial and Professional Regulation";
                            default -> stateName + " Banking Department";
                        };
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%CODE%", s.code())
                .replace("%NAME%", s.name())
                .replace("%REGION%", s.region())
                .replace("%TAX%", s.salesTaxRate())
                .replace("%FDIC%", s.fdicRegion());
    }

    static String disclosures(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.time.LocalDate;
                import java.util.ArrayList;
                import java.util.List;

                /**
                 * State-specific disclosure overlays for %FOUND% in %NAME%.
                 * Layered on top of the national disclosure, these capture
                 * items that only apply under %CODE% law (UDAP, UIPA, unclaimed
                 * property reporting, language access, electronic signature).
                 */
                public final class %CLS%Disclosures {

                    private final %CLS%Profile profile;

                    public %CLS%Disclosures() {
                        this.profile = new %CLS%Profile();
                    }

                    public %CLS%Disclosures(%CLS%Profile profile) {
                        this.profile = profile;
                    }

                    public List<String> stateSpecificAdditions() {
                        List<String> items = new ArrayList<>();
                        items.add(stateHeader());
                        items.add(regulatoryAuthorityClause());
                        items.add(unclaimedPropertyClause());
                        items.add(electronicSignatureClause());
                        if (profile.offersSpanishLanguageSupport()) {
                            items.add(languageAccessClause());
                        }
                        if (profile.requiresPrintedDisclosure()) {
                            items.add(printedCopyRequiredClause());
                        }
                        if (profile.isNoSalesTaxState()) {
                            items.add(noSalesTaxClause());
                        }
                        return items;
                    }

                    public String stateHeader() {
                        return "%NAME% Residents Disclosure — Effective "
                                + LocalDate.of(2026, 1, 1)
                                + ". This supplement is part of the %FOUND% account agreement.";
                    }

                    public String regulatoryAuthorityClause() {
                        return "This product is offered subject to the rules of "
                                + profile.stateBankingAuthority()
                                + " and federal banking regulations. Consumer complaints may be directed to "
                                + profile.stateBankingAuthority() + ".";
                    }

                    public String unclaimedPropertyClause() {
                        return "%NAME% unclaimed property law requires abandoned funds to be "
                                + "escheated to the state after "
                                + profile.escheatmentDormancyYears()
                                + " years of inactivity. Notice will be mailed prior to escheatment.";
                    }

                    public String electronicSignatureClause() {
                        return "By consenting to electronic delivery, you agree that disclosures, "
                                + "statements, and notices for this %FOUND% account may be delivered "
                                + "electronically. You may withdraw consent at any time.";
                    }

                    public String languageAccessClause() {
                        return "This account disclosure is available in Spanish upon request. "
                                + "Llame a nuestro centro de servicio para recibir una copia en español.";
                    }

                    public String printedCopyRequiredClause() {
                        return "A printed copy of this disclosure will be provided at account opening "
                                + "as required by %NAME% law, in addition to any electronic copy delivered.";
                    }

                    public String noSalesTaxClause() {
                        return "%NAME% does not impose sales tax on bank service fees; "
                                + "fees listed in the schedule are the total charged to you.";
                    }

                    public String renderFullSupplement() {
                        StringBuilder sb = new StringBuilder();
                        sb.append("=".repeat(70)).append("\\n");
                        sb.append("%FOUND% — %NAME% State Disclosure Supplement\\n");
                        sb.append("=".repeat(70)).append("\\n\\n");
                        for (String item : stateSpecificAdditions()) {
                            sb.append(item).append("\\n\\n");
                        }
                        return sb.toString();
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%CODE%", s.code())
                .replace("%NAME%", s.name());
    }

    static String regulatoryFilings(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.time.LocalDate;
                import java.time.YearMonth;
                import java.util.ArrayList;
                import java.util.List;

                /**
                 * State regulatory filing cadence for %FOUND% in %NAME%.
                 * Filings are separate from federal FFIEC reports and vary by
                 * state. This class produces the filing calendar and metadata
                 * needed for the batch-processing module to enqueue them.
                 */
                public final class %CLS%RegulatoryFilings {

                    public record Filing(
                            String code,
                            String label,
                            String cadence,
                            LocalDate nextDueDate,
                            String filingAuthority,
                            boolean electronic
                    ) {}

                    private final %CLS%Profile profile;

                    public %CLS%RegulatoryFilings() {
                        this(new %CLS%Profile());
                    }

                    public %CLS%RegulatoryFilings(%CLS%Profile profile) {
                        this.profile = profile;
                    }

                    public List<Filing> quarterlyFilings(YearMonth quarter) {
                        List<Filing> filings = new ArrayList<>();
                        LocalDate dueDate = quarter.atEndOfMonth().plusDays(30);

                        filings.add(new Filing(
                                "STATE_CONDITION_REPORT",
                                "%NAME% Condition Report",
                                "QUARTERLY",
                                dueDate,
                                profile.stateBankingAuthority(),
                                true
                        ));

                        filings.add(new Filing(
                                "UNCLAIMED_PROPERTY",
                                "Unclaimed Property Pre-Notice (%NAME%)",
                                "ANNUAL",
                                LocalDate.of(dueDate.getYear(), 10, 31),
                                profile.stateBankingAuthority(),
                                true
                        ));

                        if (profile.stateCode().equals("NY")) {
                            filings.add(new Filing(
                                    "NYS_23A_FILING",
                                    "NYS Section 23 Quarterly Activity Report",
                                    "QUARTERLY",
                                    dueDate,
                                    profile.stateBankingAuthority(),
                                    true
                            ));
                        }
                        if (profile.stateCode().equals("CA")) {
                            filings.add(new Filing(
                                    "CA_FI_FINANCIAL_CODE_332",
                                    "California Financial Code §332 Report",
                                    "QUARTERLY",
                                    dueDate,
                                    profile.stateBankingAuthority(),
                                    true
                            ));
                        }
                        if (profile.stateCode().equals("TX")) {
                            filings.add(new Filing(
                                    "TX_FIN_CODE_34_201",
                                    "Texas Finance Code §34.201 Quarterly",
                                    "QUARTERLY",
                                    dueDate,
                                    profile.stateBankingAuthority(),
                                    true
                            ));
                        }

                        return filings;
                    }

                    public List<Filing> annualFilings(int year) {
                        List<Filing> filings = new ArrayList<>();
                        filings.add(new Filing(
                                "ANNUAL_COMPLIANCE_CERT",
                                "Annual State Compliance Certification",
                                "ANNUAL",
                                LocalDate.of(year, 3, 31),
                                profile.stateBankingAuthority(),
                                true
                        ));

                        filings.add(new Filing(
                                "STATE_ESCHEATMENT_REPORT",
                                "Unclaimed Property Remittance (%NAME%)",
                                "ANNUAL",
                                LocalDate.of(year, 11, 1),
                                profile.stateBankingAuthority(),
                                true
                        ));

                        return filings;
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%NAME%", s.name());
    }

    static String rateTable(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.math.BigDecimal;
                import java.time.LocalDate;
                import java.util.ArrayList;
                import java.util.Collections;
                import java.util.List;

                /**
                 * State-specific rate table overlay for %FOUND% offered in %NAME%.
                 * In markets where the bank competes aggressively, rates may be
                 * bumped above the national posted rate. In regulated-rate states
                 * the table is clamped by state law.
                 */
                public final class %CLS%RateTable {

                    public record RateBand(BigDecimal lowerInclusive, BigDecimal upperExclusive, BigDecimal apy) {}

                    private final List<RateBand> bands;
                    private final LocalDate effectiveFrom;
                    private final String rateSheetRef;

                    public %CLS%RateTable() {
                        this.effectiveFrom = LocalDate.of(2026, 1, 1);
                        this.rateSheetRef = "RATE-%CODE%-%FOUND%-2026Q1";
                        this.bands = buildBands();
                    }

                    public List<RateBand> bands() {
                        return Collections.unmodifiableList(bands);
                    }

                    public LocalDate effectiveFrom() { return effectiveFrom; }
                    public String rateSheetRef() { return rateSheetRef; }

                    public BigDecimal apyFor(BigDecimal balance) {
                        RateBand match = null;
                        for (RateBand b : bands) {
                            if (balance.compareTo(b.lowerInclusive()) >= 0
                                    && (b.upperExclusive() == null
                                            || balance.compareTo(b.upperExclusive()) < 0)) {
                                match = b;
                            }
                        }
                        return match != null ? match.apy() : BigDecimal.ZERO;
                    }

                    public BigDecimal topTierApy() {
                        return bands.isEmpty()
                                ? BigDecimal.ZERO
                                : bands.get(bands.size() - 1).apy();
                    }

                    private List<RateBand> buildBands() {
                        List<RateBand> out = new ArrayList<>();
                        BigDecimal adjustment = stateRateAdjustment();
                        BigDecimal baseApy = new BigDecimal("0.0300").add(adjustment);
                        out.add(new RateBand(
                                BigDecimal.ZERO,
                                new BigDecimal("1000"),
                                baseApy));
                        out.add(new RateBand(
                                new BigDecimal("1000"),
                                new BigDecimal("10000"),
                                baseApy.add(new BigDecimal("0.0010"))));
                        out.add(new RateBand(
                                new BigDecimal("10000"),
                                new BigDecimal("100000"),
                                baseApy.add(new BigDecimal("0.0025"))));
                        out.add(new RateBand(
                                new BigDecimal("100000"),
                                null,
                                baseApy.add(new BigDecimal("0.0050"))));
                        return out;
                    }

                    private BigDecimal stateRateAdjustment() {
                        return switch ("%CODE%") {
                            // High competition markets — bump rates slightly
                            case "CA", "NY", "TX", "FL", "IL" -> new BigDecimal("0.0025");
                            // Online-heavy markets
                            case "MA", "NJ", "CT" -> new BigDecimal("0.0015");
                            default -> BigDecimal.ZERO;
                        };
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%CODE%", s.code())
                .replace("%NAME%", s.name());
    }

    static String branchIntegration(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.util.List;
                import java.util.Objects;

                /**
                 * Branch / channel integration metadata for %FOUND% in %NAME%.
                 * Tells the customer-portal and in-branch teller system which
                 * workflows to show and which regional call-center queue to use.
                 */
                public final class %CLS%BranchIntegration {

                    public record Channel(String code, String displayName, boolean active, String regionQueue) {
                        public Channel {
                            Objects.requireNonNull(code);
                            Objects.requireNonNull(displayName);
                        }
                    }

                    private final %CLS%Profile profile;

                    public %CLS%BranchIntegration() {
                        this.profile = new %CLS%Profile();
                    }

                    public %CLS%BranchIntegration(%CLS%Profile profile) {
                        this.profile = profile;
                    }

                    public List<Channel> availableChannels() {
                        return List.of(
                                new Channel("WEB", "Online Banking", true, queueFor("WEB")),
                                new Channel("MOBILE", "Mobile App", true, queueFor("MOBILE")),
                                new Channel("BRANCH", "Branch", hasBranches(), queueFor("BRANCH")),
                                new Channel("ATM", "ATM Network", true, queueFor("ATM")),
                                new Channel("CALL_CENTER", "Phone Banking", true,
                                        profile.offersSpanishLanguageSupport()
                                                ? queueFor("CALL_CENTER") + "_BILINGUAL"
                                                : queueFor("CALL_CENTER"))
                        );
                    }

                    private String queueFor(String channel) {
                        return profile.region() + "_" + channel;
                    }

                    private boolean hasBranches() {
                        return switch (profile.stateCode()) {
                            // Digital-first states with limited physical footprint
                            case "AK", "ND", "SD", "WY", "MT" -> false;
                            default -> true;
                        };
                    }

                    public String primaryCallCenterQueue() {
                        return queueFor("CALL_CENTER");
                    }

                    public boolean channelActive(String channelCode) {
                        return availableChannels().stream()
                                .anyMatch(c -> c.code().equals(channelCode) && c.active());
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%NAME%", s.name());
    }

    static String profileTest(String pkg, String cls, String foundation, StateSpec s) {
        return """
                package %PKG%;

                import java.math.BigDecimal;
                import java.time.YearMonth;
                import org.junit.jupiter.api.Test;
                import static org.assertj.core.api.Assertions.assertThat;

                class %CLS%ProfileTest {

                    @Test
                    void profile_reports_expected_state_code() {
                        var p = new %CLS%Profile();
                        assertThat(p.stateCode()).isEqualTo("%CODE%");
                        assertThat(p.stateName()).isEqualTo("%NAME%");
                    }

                    @Test
                    void apply_state_fee_tax_is_non_decreasing() {
                        var p = new %CLS%Profile();
                        var taxed = p.applyStateFeeTax(new BigDecimal("10.00"));
                        assertThat(taxed).isGreaterThanOrEqualTo(new BigDecimal("10.00"));
                    }

                    @Test
                    void rate_table_returns_positive_apy_for_low_balance() {
                        var rt = new %CLS%RateTable();
                        var apy = rt.apyFor(new BigDecimal("500"));
                        assertThat(apy.signum()).isGreaterThan(0);
                    }

                    @Test
                    void rate_table_top_tier_is_highest() {
                        var rt = new %CLS%RateTable();
                        var top = rt.topTierApy();
                        var low = rt.apyFor(new BigDecimal("100"));
                        assertThat(top).isGreaterThanOrEqualTo(low);
                    }

                    @Test
                    void disclosures_contain_state_name() {
                        var d = new %CLS%Disclosures();
                        assertThat(d.renderFullSupplement()).contains("%NAME%");
                    }

                    @Test
                    void regulatory_filings_produced_for_quarter() {
                        var f = new %CLS%RegulatoryFilings();
                        var filings = f.quarterlyFilings(YearMonth.of(2026, 3));
                        assertThat(filings).isNotEmpty();
                    }

                    @Test
                    void channel_integration_lists_web_and_mobile() {
                        var b = new %CLS%BranchIntegration();
                        assertThat(b.channelActive("WEB")).isTrue();
                        assertThat(b.channelActive("MOBILE")).isTrue();
                    }
                }
                """
                .replace("%PKG%", pkg)
                .replace("%CLS%", cls)
                .replace("%FOUND%", foundation)
                .replace("%CODE%", s.code())
                .replace("%NAME%", s.name());
    }
}
