package com.aibench.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.List;

/**
 * Phase C / Layer 3 — SWIFT message-handler variant of
 * {@link RegionalScenarioTestGenerator}. Walks
 * {@code banking-app/generated-swift/} and writes a
 * {@code <Mt###>ScenarioMatrixTest.java} alongside the existing handler
 * test for each of the 46 message-type modules.
 *
 * <p>Each generated file contains roughly 20 @Test methods covering the
 * Handler/Parser/Validator/RoutingRules public APIs that are common across
 * every MT type.
 *
 * <p>Idempotent.
 */
public class SwiftScenarioTestGenerator {

    public static void main(String[] args) throws IOException {
        Path swiftRoot = resolveRoot(args);
        if (!Files.isDirectory(swiftRoot)) {
            throw new IllegalStateException("generated-swift not found at " + swiftRoot);
        }

        List<Path> moduleDirs;
        try (var stream = Files.list(swiftRoot)) {
            moduleDirs = stream.filter(Files::isDirectory).sorted().toList();
        }

        int generated = 0;
        long totalLoc = 0;
        for (Path moduleDir : moduleDirs) {
            ModuleInfo info = inspectModule(moduleDir);
            if (info == null) continue;
            String src = scenarioTest(info);
            Path testFile = info.testDir.resolve(info.classPrefix + "ScenarioMatrixTest.java");
            Files.createDirectories(testFile.getParent());
            Files.writeString(testFile, src, StandardCharsets.UTF_8);
            generated++;
            totalLoc += src.lines().count();
        }
        System.out.println("Generated " + generated + " SWIFT scenario tests (~"
                + totalLoc + " LOC)");
    }

    private static Path resolveRoot(String[] args) {
        if (args.length > 0) return Paths.get(args[0]);
        Path cwd = Paths.get("").toAbsolutePath();
        for (int i = 0; i < 4; i++) {
            Path candidate = cwd.resolve("banking-app").resolve("generated-swift");
            if (Files.isDirectory(candidate)) return candidate;
            if (cwd.getParent() == null) break;
            cwd = cwd.getParent();
        }
        throw new IllegalStateException("Cannot find banking-app/generated-swift");
    }

    private static ModuleInfo inspectModule(Path moduleDir) throws IOException {
        Path mainJava = moduleDir.resolve("src/main/java");
        if (!Files.isDirectory(mainJava)) return null;

        Path handlerFile;
        try (var stream = Files.walk(mainJava)) {
            handlerFile = stream
                    .filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith("Handler.java"))
                    .min(Comparator.comparing(Path::toString))
                    .orElse(null);
        }
        if (handlerFile == null) return null;

        String fileName = handlerFile.getFileName().toString();
        String classPrefix = fileName.substring(0, fileName.length() - "Handler.java".length());
        String pkg = readPackage(handlerFile);
        if (pkg == null) return null;

        Path testDir = moduleDir.resolve("src/test/java/" + pkg.replace('.', '/'));
        return new ModuleInfo(pkg, classPrefix, testDir);
    }

    private static String readPackage(Path javaFile) throws IOException {
        for (String line : Files.readAllLines(javaFile, StandardCharsets.UTF_8)) {
            String trimmed = line.trim();
            if (trimmed.startsWith("package ") && trimmed.endsWith(";")) {
                return trimmed.substring("package ".length(), trimmed.length() - 1).trim();
            }
        }
        return null;
    }

    private static String scenarioTest(ModuleInfo info) {
        return ("""
                package %PKG%;

                import org.junit.jupiter.api.Test;
                import static org.assertj.core.api.Assertions.assertThat;
                import static org.assertj.core.api.Assertions.assertThatThrownBy;

                /**
                 * Auto-generated scenario tests for the %PREFIX% SWIFT message handler.
                 * Generated by {@code com.aibench.codegen.SwiftScenarioTestGenerator}.
                 *
                 * <p>Coverage: handler counters, parser-input handling, validator
                 * findings shape, routing decisions, message-type classification,
                 * intra-group BIC detection, high-value-priority override.
                 */
                class %PREFIX%ScenarioMatrixTest {

                    private static final String VALID_BIC_BLOCK =
                            "sender=OMNIUS33XXX\\nreceiver=CHASUS33XXX\\n:20:REF\\n";

                    private final %PREFIX%Handler handler = new %PREFIX%Handler();
                    private final %PREFIX%Parser parser = new %PREFIX%Parser();
                    private final %PREFIX%Validator validator = new %PREFIX%Validator();
                    private final %PREFIX%RoutingRules routing = new %PREFIX%RoutingRules();

                    @Test
                    void handler_null_input_throws_npe() {
                        assertThatThrownBy(() -> handler.handle(null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void handler_empty_input_is_processed_but_rejected() {
                        var result = handler.handle("");
                        assertThat(result).isNotNull();
                        assertThat(result.accepted()).isFalse();
                    }

                    @Test
                    void handler_counters_increment_per_invocation() {
                        long before = handler.processedCount();
                        handler.handle("");
                        handler.handle("");
                        handler.handle("");
                        assertThat(handler.processedCount() - before).isEqualTo(3);
                    }

                    @Test
                    void handler_accepted_plus_rejected_equals_processed() {
                        handler.handle("");
                        handler.handle(":20:REF1\\nsender=OMNIUS33XXX\\nreceiver=CHASUS33XXX\\n");
                        assertThat(handler.acceptedCount() + handler.rejectedCount())
                                .isEqualTo(handler.processedCount());
                    }

                    @Test
                    void parser_null_throws_npe() {
                        assertThatThrownBy(() -> parser.parse(null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void parser_minimal_valid_input_returns_message_with_required_fields() {
                        var msg = parser.parse(VALID_BIC_BLOCK);
                        assertThat(msg).isNotNull();
                        assertThat(msg.senderBic()).isNotBlank();
                        assertThat(msg.receiverBic()).isNotBlank();
                    }

                    @Test
                    void parser_well_formed_message_round_trips_reference() {
                        String block = "sender=OMNIUS33XXX\\n"
                                + "receiver=CHASUS33XXX\\n"
                                + ":20:TESTREF1\\n"
                                + ":32A:260416USD1000,00\\n"
                                + ":59:BENEFICIARY\\n"
                                + ":70:DETAILS\\n";
                        var msg = parser.parse(block);
                        assertThat(msg.messageReference()).isEqualTo("TESTREF1");
                    }

                    @Test
                    void validator_null_message_throws_npe() {
                        assertThatThrownBy(() -> validator.validate(null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void validator_returns_result_with_non_null_findings_list() {
                        var msg = parser.parse(VALID_BIC_BLOCK);
                        var result = validator.validate(msg);
                        assertThat(result).isNotNull();
                        assertThat(result.findings()).isNotNull();
                    }

                    @Test
                    void validator_isvalid_consistent_with_haserrors() {
                        var msg = parser.parse(":20:OK\\nsender=OMNIUS33XXX\\nreceiver=CHASUS33XXX\\n");
                        var result = validator.validate(msg);
                        assertThat(result.isValid()).isEqualTo(!result.hasErrors());
                    }

                    @Test
                    void routing_returns_non_null_destination_for_any_message() {
                        var msg = parser.parse("sender=OMNIUS33XXX\\nreceiver=CHASUS33XXX\\n");
                        assertThat(routing.routeFor(msg)).isNotNull();
                    }

                    @Test
                    void routing_throws_npe_for_null_message() {
                        assertThatThrownBy(() -> routing.routeFor(null))
                                .isInstanceOf(NullPointerException.class);
                    }

                    @Test
                    void routing_intra_group_recognizes_bank_prefix() {
                        assertThat(routing.isIntraGroup("OMNIUS33XXX")).isTrue();
                    }

                    @Test
                    void routing_intra_group_null_bic_is_not_intra_group() {
                        assertThat(routing.isIntraGroup(null)).isFalse();
                    }

                    @Test
                    void routing_intra_group_external_bic_is_not_intra_group() {
                        assertThat(routing.isIntraGroup("CHASUS33XXX")).isFalse();
                    }

                    @Test
                    void routing_high_value_amount_returns_priority_queue_override() {
                        String block = "sender=OMNIUS33XXX\\n"
                                + "receiver=CHASUS33XXX\\n"
                                + ":20:BIG\\n"
                                + ":32A:260416USD20000000,00\\n"
                                + ":59:BENEFICIARY\\n";
                        var msg = parser.parse(block);
                        assertThat(routing.priorityQueueOverride(msg))
                                .isEqualTo("HIGH_VALUE_REVIEW_QUEUE");
                    }

                    @Test
                    void routing_low_value_amount_returns_null_override() {
                        String block = "sender=OMNIUS33XXX\\n"
                                + "receiver=CHASUS33XXX\\n"
                                + ":20:SMALL\\n"
                                + ":32A:260416USD100,00\\n"
                                + ":59:BENEFICIARY\\n";
                        var msg = parser.parse(block);
                        assertThat(routing.priorityQueueOverride(msg)).isNull();
                    }

                    @Test
                    void message_type_label_is_present() {
                        var msg = parser.parse(VALID_BIC_BLOCK);
                        assertThat(msg.messageType()).isNotBlank();
                    }

                    @Test
                    void message_classification_predicates_are_booleans() {
                        var msg = parser.parse(VALID_BIC_BLOCK);
                        // Just call them to ensure no NPE; results vary by MT type.
                        msg.isPayment();
                        msg.isStatement();
                        msg.requiresSettlement();
                    }

                    @Test
                    void destination_enum_includes_dead_letter_fallback() {
                        assertThat(%PREFIX%RoutingRules.Destination.values())
                                .contains(%PREFIX%RoutingRules.Destination.DEAD_LETTER_QUEUE);
                    }
                }
                """)
                .replace("%PKG%", info.pkg)
                .replace("%PREFIX%", info.classPrefix);
    }

    private record ModuleInfo(String pkg, String classPrefix, Path testDir) {}
}
